:scrollbar:
:data-uri:
:toc2:
:imagesdir: images

== Mastering Serverless PaaS with OpenShift - Lab Guide

:numbered:
== Overview

This Lab Environment uses OpenShift 3.9, and Apache OpenWhisk, as open source Function-as-a-Service (FaaS) implementation for Platform-as-a-Service (PaaS) solutions on either Private, Hybrid and Public Clouds.

Apache OpenWhisk is designed to act as an asynchronous and loosely coupled execution environment that can run functions against external triggers. 
 
The initial configuration steps include:

* Configuring the access to OpenShift Container Platform Console and Web Console
* Accessing and managing Function-as-a-Service (faas) project inside OCP
* Configure OpenWhisk CLI to access faas project

After this initial step, we will try out main object of OpenWhisk such

* Actions
* Rules
* Triggers

In particular, we will do a step by step procedure to create and run functions as *Java Actions*, *Node Actions*, *Python Actions*


.Goal
* Create Functions and consume them at scale with OpenShift Container Platform
+

Required versions of products used:

[cols="1,1",options="header"]
|=======
|Product |Version
|OpenShift Container Platform |3.9.14
|Apache OpenWhisk | rhdemo-b7724ef
|Red Hat Enterprise Linux |7.4
|=======
